name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.1'

    - name: Install dependencies
      run: |
        go version
        go install honnef.co/go/tools/cmd/staticcheck@2022.1
        
    - name: Run build
      run: go build . 

    - name: Run lint (staticcheck)
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1.1"
      
    - name: Run vet
      run: go vet .
        
    - name: Run testing
      run: go test -v